# Generated by Django 4.1.9 on 2023-06-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congress', models.IntegerField()),
                ('latest_action_date', models.DateField()),
                ('latest_action_text', models.TextField()),
                ('number', models.CharField(max_length=50)),
                ('origin_chamber', models.CharField(max_length=50)),
                ('origin_chamber_code', models.CharField(max_length=10)),
                ('title', models.TextField()),
                ('bill_type', models.CharField(max_length=50)),
                ('update_date', models.DateField()),
                ('update_date_including_text', models.DateTimeField()),
                ('url', models.URLField()),
            ],
        ),
    ]
