# Generated by Django 4.1.9 on 2023-06-18 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polistackapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bill',
            table='bill',
        ),
    ]
